### ISSUE TITLE
./run.sh script fails due to Maven issue

### ISSUE THREAD

**Issue by mvolkmann** [perfectsense/brightspot-tutorial#14]
I ame using Java 1.8.0_191 and get this output:
[WARNING] The requested profile "run" could not be activated because it does not exist.
[ERROR] Plugin com.psddev:styleguide-maven-plugin:4.0-SNAPSHOT or one of its dependencies could not be resolved: Failure to transfer com.psddev:styleguide-maven-plugin:jar:4.0-20190703.141402-158 from https://artifactory.psdops.com/public was cached in the local repository, resolution will not be reattempted until the update interval of public.psddev has elapsed or updates are forced. Original error: Could not transfer artifact com.psddev:styleguide-maven-plugin:jar:4.0-2I /Users/e086922/brightspot/brightspot-tutorial-master/init

**Comment by danslaughter2** [comment]
Archiving repo.
