### ISSUE TITLE
gulp styleguide not works.

### ISSUE THREAD

**Issue by ahunga-pei** [perfectsense/brightspot-tutorial#21]
I am following the tutorial guide https://docs.brightspot.com/4.2/en/developer-guide/tutorial/lesson-2--creating-a-front-end.html.

and failed at `gulp styleguide`

**Comment by ahunga-pei** [comment]
cc: @AndrewJMiller

**Comment by jtorralbagithub** [comment]
I got an error as well until I switched to node v8.11.1 (same version shown here: https://gulpjs.com/docs/en/getting-started/quick-start/).  `gulp styleguide` worked for me after using this version.

**Comment by danslaughter2** [comment]
Archiving repo.
