### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by swit1983** [perfectsense/brightspot-tutorial#6]
[INFO] No proxies configured
[INFO] No proxy was configured, downloading directly
七月 25, 2017 4:12:20 下午 org.apache.http.impl.execchain.RetryExec execute
信息: I/O exception (java.net.SocketException) caught when processing request to
 {s}->https://nodejs.org:443: Software caused connection abort: recv failed
七月 25, 2017 4:12:20 下午 org.apache.http.impl.execchain.RetryExec execute
信息: Retrying request to {s}->https://nodejs.org:443
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:47 min
[INFO] Finished at: 2017-07-25T16:12:57+08:00
[INFO] Final Memory: 27M/258M
[INFO] ------------------------------------------------------------------------
[WARNING] The requested profile "run" could not be activated because it does not
 exist.
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.2:ins
tall-node-and-yarn (install-node-and-yarn) on project tutorial-init: Could not d
ownload Node.js from: https://nodejs.org/dist/v6.9.1/win-x64/node.exe: Could not
 download https://nodejs.org/dist/v6.9.1/win-x64/node.exe: Remote host closed co
nnection during handshake: SSL peer shut down incorrectly -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureExc
eption

**Comment by tomasdev** [comment]
Having the same issue.

(Also unrelated, had to remove all `^M` chars using `sed -i -e 's/\r$//' filename` in order for these to be run in *NIX and prevent the `bash: ./run.sh: /bin/bash^M: bad interpreter: No such file or directory`)

**Comment by tomasdev** [comment]
Make sure your $MAVEN_CONFIG is empty. (`export MAVEN_CONFIG=""`)
Make sure you can access https://nodejs.org

**Comment by danslaughter2** [comment]
Archiving repo.
